# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # config.ssh.tty = true
  # config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # config.vm.boot_timeout = 300

  # eval File.read("machines/windows-10.rb")

  # eval File.read("machines/kali.rb")

  # eval File.read("machines/ubuntu_xenial_apache.rb")
  
  # eval File.read("machines/laravel.rb")
  
  eval File.read("machines/ubuntu_xenial.rb")
  
  # eval File.read("machines/debian_jessie.rb")


  # config.vm.provider "docker" do |d|
  #   d.image = "kalilinux/kali-rolling"
  # end

end
